// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBkKna-bWxISxsyHQz6dCrKfr7z7DC6GfM',
    appId: '1:823355742434:web:111d914566fb213367e6bb',
    messagingSenderId: '823355742434',
    projectId: 'samparka-44552',
    authDomain: 'samparka-44552.firebaseapp.com',
    storageBucket: 'samparka-44552.firebasestorage.app',
    measurementId: 'G-Y9B88B7DWF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAm1_AXxq-xjBoSPAKaU_AwzL2NBjGBSC8',
    appId: '1:823355742434:android:435e17b2445174e267e6bb',
    messagingSenderId: '823355742434',
    projectId: 'samparka-44552',
    storageBucket: 'samparka-44552.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyApkbHJP_Ibqb7FN4x7hYU2isIoMPCdq7c',
    appId: '1:823355742434:ios:7ed33a9cef89642167e6bb',
    messagingSenderId: '823355742434',
    projectId: 'samparka-44552',
    storageBucket: 'samparka-44552.firebasestorage.app',
    iosBundleId: 'com.Samparka.samparka',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyApkbHJP_Ibqb7FN4x7hYU2isIoMPCdq7c',
    appId: '1:823355742434:ios:7ed33a9cef89642167e6bb',
    messagingSenderId: '823355742434',
    projectId: 'samparka-44552',
    storageBucket: 'samparka-44552.firebasestorage.app',
    iosBundleId: 'com.Samparka.samparka',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBkKna-bWxISxsyHQz6dCrKfr7z7DC6GfM',
    appId: '1:823355742434:web:4181f0f7171d846967e6bb',
    messagingSenderId: '823355742434',
    projectId: 'samparka-44552',
    authDomain: 'samparka-44552.firebaseapp.com',
    storageBucket: 'samparka-44552.firebasestorage.app',
    measurementId: 'G-N6JDVRG9M4',
  );
}
